# docker-compose.test.yml
version: '3.8'
services:
  db:
    container_name: test-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST} 
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${TEST_POSTGRES_DB} 
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local