version: '3.9'
services:
  api:
    container_name: student-rest-api
    image: student-rest-api:0.0.1
    volumes:
      - postgres-data:/app/postgres-data
    build: .
    ports:
      - '8000:3000'
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "npm run && npm run start:migrate:prod"
  db:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env      
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    name: postgres-data
